# Generated by Django 3.2.7 on 2022-06-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='detailed_description',
            field=models.CharField(db_index=True, max_length=10000, verbose_name='Detailed Description'),
        ),
    ]
