# Generated by Django 3.2.7 on 2022-07-22 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_detailed_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place_type',
        ),
        migrations.RemoveField(
            model_name='place',
            name='time_to_travel',
        ),
    ]
